sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t kracklabs/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kracklabs/react-test npm test


after_success:
  - docker build -t kracklabs/multi-client ./client
  - docker build -t kracklabs/multi-server ./server
  - docker build -t kracklabs/multi-nginx ./nginx
  - docker build -t kracklabs/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push kracklabs/multi-client
  - docker push kracklabs/multi-server
  - docker push kracklabs/multi-nginx
  - docker push kracklabs/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-2'
  app: 'docker-multi2'
  env: 'DockerMulti2-env'
  bucket_name: 'elasticbeanstalk-eu-west-2-959206288261'
  bucket_path: 'docker-multi2'
  on:
    branch: master
  access_key_id: $access_key_id
  secret_access_key: $secret_access_key
